=== we4tech/interactive-textual-response--itr-/itr-common/src/main/resources/schema/navigation.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://idea-sense.com/navigation" elementFormDefault="qualified" xmlns="http://idea-sense.com/navigation" xmlns:mstns="http://idea-sense.com/navigation" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Navigation">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Service-welcome-message">
          <xs:complexType>
            <xs:sequence>
              <xs:group ref="responseGroup" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Service-index">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Index" type="IndexType" minOccurs="1" maxOccurs='unbounded' />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="echoType" id="echoType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="plug-inType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="IndexType">
    <xs:sequence>
      <xs:group ref="indexResponseGroup" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="keyCode" type="xs:string" />
    <xs:attribute name="title" type="xs:string" />
  </xs:complexType>
  <xs:group name="responseGroup">
    <xs:choice>
      <xs:element name="echo" type="xs:string">
      </xs:element>
      <xs:element name="plug-in" type="xs:string" />
    </xs:choice>
  </xs:group>
  <xs:group name="indexResponseGroup">
    <xs:choice>
      <xs:group ref="responseGroup" />
      <xs:element name="Index" type="IndexType" maxOccurs='unbounded' />
    </xs:choice>
  </xs:group>
</xs:schema>

=== we4tech/interactive-textual-response--itr-/itr-base/src/main/resources/config/companies/ideasense.xml
<?xml version="1.0" encoding="UTF-8" ?>
    <!--
      xmlns="http://idea-sense.com/navigation"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://idea-sense.com/navigation navigation.xsd"
    -->
<Navigation>

  <!--+
      | Interact on different kind of error level.
      +-->
  <ResponseMap>
    <invalidCommandError>
      <echo>Invalid command found</echo>
    </invalidCommandError>
    <internalError>
      <echo>Internal error occured.</echo>
    </internalError>
    <helpCommand>
      <echo>Help stuff here...</echo>
    </helpCommand>
    <systemCommandSuccessful>
      <echo>Successfully executed your command.</echo>
    </systemCommandSuccessful>
    <systemCommandFailed>
      <echo>Failed to execute your command.</echo>
    </systemCommandFailed>
  </ResponseMap>
  <!--+
      | This message is printed as welcome message, when user enter the messenger
      | or send the first message.
      +-->
  <Service-welcome-message>
    <echo>
      স্বগতম IDEASense এর ITR service এ
      এখন বাজে - ${date}
    </echo>
  </Service-welcome-message>

  <!--+
      | List of available services
      +-->
  <Service-index>
    <Index keyCode="1" title="এখন কয়টা বাজে?">
      <echo>
        এখন বাজে- ${time}
      </echo>
    </Index>
    <Index keyCode="2" title="বাংলা টেস্ট সারভিস">
      <echo lang="en">Just tested, now how does it look?</echo>
      <echo>টেস্ট করলাম, এখন কেমন লাগল :)</echo>
      <Index keyCode="2.1" title="ITR কি?">
        <echo><![CDATA[
        ITR হল Interactive Textual Response.
        ]]></echo>
      </Index>
      <Index keyCode="2.2" title="কি কাজে ব্যবহার হতে পারে?">
        <echo>
          আপনার কম্পানির সারভিসITR এর সাহায্যে interactivly উপস্থপন করতে পারেন
        </echo>
        <Index keyCode="2.2.1" title="এটা কি open source?">
          <echo>
            আসা করি তারা তারি এটা ওপেন সোর্স করা হেব
          </echo>
        </Index>
      </Index>
      <Index keyCode="2.3" title="plug-in টা কিভাবে সাপর্ট করে?">
        <Index keyCode="2.3.1" title="একটা উদাহরন স্বরুপ দেখাও?">
          <echo><![CDATA[
            এই টেগ টা ব্যবহার করতে হবে <Index/> ট্যগ এর মধ্যে-
            <plug-in>http://localhost/test.php</plug-in>
          ]]></echo>
        </Index>
        <Index keyCode="2.3.2" title="সত্যিকারের একটা plug-in রান করে দেখাও">
          <plug-in>http://localhost/test.php</plug-in>
          <plug-in lang="en">http://localhost/test.php</plug-in>
        </Index>
      </Index>
    </Index>
  </Service-index>
</Navigation>
